apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: airflow-gcloud:latest
          env:
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: config
              mountPath: /opt/airflow/config
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-airflow
          resources:
            limits:
              memory: "200Mi"
          volumeMounts:
            - name: logs
              mountPath: /fluentd/log
      initContainers:
        - name: fetch-dags
          image: google/cloud-sdk:slim
          command: ["/bin/sh", "-c"]
          args:
            - gsutil -m cp -r gs://ntt-test-data-bq-looker-scripts/airflow/dag/* /dags/ && gsutil -m cp -r gs://ntt-test-data-bq-looker-scripts/airflow/config/* /config/;
          volumeMounts:
            - name: dags
              mountPath: /dags
            - name: config
              mountPath: /config
      volumes:
        - name: dags
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: airflow
spec:
  selector:
    app: airflow
  ports:
    - port: 8080
      targetPort: 8080
      name: web
